# Generated by Django 5.0.6 on 2024-05-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bookmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('bus', 'Bus'), ('restaurant', 'Restaurant')], default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
