# Generated by Django 5.0.6 on 2024-05-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favorite_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='category',
        ),
    ]
