# Generated by Django 5.0.6 on 2024-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bus_hotel_restaurant_remove_favorite_row_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='favorite',
            name='row_data',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
